[project]
name = "de-exercise-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.5.6",
    "pandas>=3.0.6",
    "psycopg2>=2.9.13",
    "sqlalchemy>=2.0.54",
]

[dependency-groups]
dev = [
    "apache-airflow>=3.3.2",
    "ipykernel>=7.3.0",
]
